# SAM Cognitive Memory Core - Graph Ontology Definition
# This ontology defines the structured knowledge representation for SAM's hybrid memory system
# Combining vector embeddings with graph-based relationships for true conceptual understanding

version: "1.0"
created: "2025-06-17"
description: "Enhanced ontology for SAM's Cognitive Memory Core with comprehensive node and edge types"

# =============================================================================
# NODE TYPES - Entities that can exist in SAM's knowledge graph
# =============================================================================

node_types:
  # Core Knowledge Entities
  - Person:
      description: "Individual people mentioned in conversations, documents, or web sources"
      properties: ["name", "role", "organization", "expertise", "contact_info"]
      examples: ["John Doe", "Dr. Sarah Chen", "CEO of TechCorp"]
      
  - Company:
      description: "Organizations, businesses, institutions, and corporate entities"
      properties: ["name", "industry", "size", "location", "founded", "website"]
      examples: ["OpenAI", "Stanford University", "NASA"]
      
  - Document:
      description: "Files, papers, reports, and written materials ingested by SAM"
      properties: ["title", "author", "type", "date", "source", "format", "size"]
      examples: ["Research Paper", "Meeting Notes", "Technical Manual"]
      
  - Technology:
      description: "Tools, frameworks, programming languages, and technical concepts"
      properties: ["name", "category", "version", "vendor", "purpose", "maturity"]
      examples: ["Python", "Kubernetes", "Machine Learning", "REST API"]
      
  - Location:
      description: "Geographic places, addresses, and spatial references"
      properties: ["name", "type", "coordinates", "country", "region", "timezone"]
      examples: ["San Francisco", "Building A Room 101", "Remote"]

  # SAM-Specific Cognitive Entities
  - Concept:
      description: "Abstract ideas, principles, and conceptual knowledge discovered by SAM"
      properties: ["name", "definition", "domain", "complexity", "confidence", "derived_from"]
      examples: ["Artificial Intelligence", "Project Management", "Data Privacy"]
      
  - Memory:
      description: "Individual memory instances stored in SAM's vector store"
      properties: ["content", "timestamp", "type", "confidence", "source", "embedding_id"]
      examples: ["Conversation snippet", "Document chunk", "Web search result"]
      
  - Conversation:
      description: "Chat sessions and dialogue interactions with users"
      properties: ["session_id", "start_time", "end_time", "participant", "topic", "summary"]
      examples: ["Daily standup chat", "Technical support session", "Planning discussion"]
      
  - Task:
      description: "Actions, assignments, and work items identified or managed by SAM"
      properties: ["title", "description", "status", "priority", "assignee", "due_date"]
      examples: ["Code review", "Write documentation", "Schedule meeting"]
      
  - Goal:
      description: "Objectives, targets, and desired outcomes tracked by SAM"
      properties: ["title", "description", "status", "target_date", "success_criteria", "owner"]
      examples: ["Launch new feature", "Improve performance", "Learn new skill"]

  # Web Integration Entities
  - WebSource:
      description: "External websites, APIs, and online resources accessed by SAM"
      properties: ["url", "domain", "title", "type", "credibility", "last_accessed"]
      examples: ["news.ycombinator.com", "GitHub repository", "Stack Overflow"]
      
  - SearchResult:
      description: "Individual results from web searches performed by SAM"
      properties: ["query", "title", "snippet", "url", "rank", "timestamp", "relevance"]
      examples: ["Google search result", "API response", "RSS feed item"]
      
  - Citation:
      description: "References and source attributions for information used by SAM"
      properties: ["source", "page", "section", "quote", "confidence", "verification_status"]
      examples: ["Research paper citation", "Web article reference", "Expert quote"]

  # Reasoning and Analysis Entities
  - Insight:
      description: "Discoveries, patterns, and implicit knowledge generated by SAM's reasoning"
      properties: ["description", "confidence", "evidence", "reasoning_path", "impact"]
      examples: ["Performance bottleneck identified", "User behavior pattern", "Market trend"]
      
  - Question:
      description: "Queries, problems, and information needs identified by SAM"
      properties: ["text", "type", "complexity", "domain", "status", "answer"]
      examples: ["How to optimize database?", "What is the project timeline?"]
      
  - Decision:
      description: "Choices, recommendations, and conclusions made by SAM"
      properties: ["description", "rationale", "alternatives", "confidence", "outcome"]
      examples: ["Technology selection", "Resource allocation", "Process improvement"]

# =============================================================================
# EDGE TYPES - Relationships that can exist between nodes
# =============================================================================

edge_types:
  # Basic Relationships
  - WORKS_FOR:
      description: "Employment or affiliation relationship"
      source_types: ["Person"]
      target_types: ["Company"]
      properties: ["role", "start_date", "end_date", "status"]
      
  - LOCATED_IN:
      description: "Physical or logical location relationship"
      source_types: ["Person", "Company", "Document"]
      target_types: ["Location"]
      properties: ["type", "since", "primary"]
      
  - MENTIONS:
      description: "Reference or citation relationship"
      source_types: ["Document", "Conversation", "SearchResult"]
      target_types: ["Person", "Company", "Technology", "Concept"]
      properties: ["context", "frequency", "sentiment"]
      
  - AUTHORED_BY:
      description: "Creation or authorship relationship"
      source_types: ["Document", "Insight", "Decision"]
      target_types: ["Person"]
      properties: ["date", "role", "contribution"]
      
  - ACQUIRED:
      description: "Acquisition or ownership relationship"
      source_types: ["Company"]
      target_types: ["Company", "Technology"]
      properties: ["date", "amount", "type"]

  # Reasoning and Knowledge Relationships
  - RELATES_TO:
      description: "General semantic relationship between concepts"
      source_types: ["Concept", "Technology", "Task", "Goal"]
      target_types: ["Concept", "Technology", "Task", "Goal"]
      properties: ["strength", "type", "discovered_by", "confidence"]
      
  - DERIVED_FROM:
      description: "Knowledge derivation or inference relationship"
      source_types: ["Concept", "Insight", "Decision"]
      target_types: ["Memory", "Document", "Conversation"]
      properties: ["reasoning_method", "confidence", "timestamp"]
      
  - CONTRADICTS:
      description: "Conflicting or opposing information relationship"
      source_types: ["Document", "SearchResult", "Insight"]
      target_types: ["Document", "SearchResult", "Insight"]
      properties: ["severity", "resolution", "verified"]
      
  - SUPPORTS:
      description: "Evidence or confirmation relationship"
      source_types: ["Document", "SearchResult", "Citation"]
      target_types: ["Concept", "Insight", "Decision"]
      properties: ["strength", "type", "verified"]

  # Web and Search Relationships
  - SEARCHED_FOR:
      description: "Web search query relationship"
      source_types: ["Person", "Conversation", "Task"]
      target_types: ["SearchResult"]
      properties: ["query", "timestamp", "success"]
      
  - CITED_BY:
      description: "Citation or reference relationship"
      source_types: ["WebSource", "Document"]
      target_types: ["Citation"]
      properties: ["page", "section", "type"]
      
  - VERIFIED_BY:
      description: "Verification or validation relationship"
      source_types: ["SearchResult", "Insight"]
      target_types: ["WebSource", "Person", "Document"]
      properties: ["method", "confidence", "timestamp"]

  # SAM Context Relationships
  - REMEMBERED_IN:
      description: "Memory storage relationship"
      source_types: ["Concept", "Person", "Technology"]
      target_types: ["Memory"]
      properties: ["embedding_id", "chunk_id", "relevance"]
      
  - DISCUSSED_IN:
      description: "Conversation topic relationship"
      source_types: ["Concept", "Task", "Goal", "Technology"]
      target_types: ["Conversation"]
      properties: ["frequency", "sentiment", "importance"]
      
  - PLANNED_FOR:
      description: "Planning and scheduling relationship"
      source_types: ["Task", "Goal"]
      target_types: ["Person", "Company", "Technology"]
      properties: ["timeline", "priority", "status"]

  # Advanced Reasoning Relationships
  - INFERRED_RELATIONSHIP:
      description: "Implicit knowledge discovered by SAM's reasoning"
      source_types: ["*"]  # Can connect any node types
      target_types: ["*"]  # Can connect any node types
      properties: ["reasoning_method", "confidence", "evidence", "discovered_at"]
      
  - TEMPORAL_SEQUENCE:
      description: "Time-based ordering relationship"
      source_types: ["Task", "Goal", "Decision", "Conversation"]
      target_types: ["Task", "Goal", "Decision", "Conversation"]
      properties: ["sequence", "duration", "causality"]
      
  - DEPENDENCY:
      description: "Prerequisite or blocking relationship"
      source_types: ["Task", "Goal", "Technology"]
      target_types: ["Task", "Goal", "Technology"]
      properties: ["type", "strength", "critical_path"]

# =============================================================================
# CONFIGURATION SETTINGS
# =============================================================================

settings:
  # Graph Database Configuration
  graph_backend: "neo4j"  # Options: neo4j, networkx, file_based
  connection_string: "bolt://localhost:7687"
  
  # Entity Extraction Configuration
  ner_model: "en_core_web_sm"  # spaCy model for Named Entity Recognition
  custom_extractors:
    - "sam_concept_extractor"    # Custom extractor for SAM-specific concepts
    - "web_source_extractor"     # Custom extractor for web sources
    - "memory_reference_extractor"  # Custom extractor for memory references
  
  # Relationship Detection Configuration
  relationship_models:
    - "dependency_parser"        # For syntactic relationships
    - "semantic_similarity"      # For semantic relationships
    - "temporal_extractor"       # For time-based relationships
  
  # Quality and Validation
  min_confidence_threshold: 0.7  # Minimum confidence for entity/relationship extraction
  max_nodes_per_document: 50     # Limit to prevent graph explosion
  enable_duplicate_detection: true
  enable_relationship_validation: true
  
  # Performance Optimization
  enable_caching: true
  cache_ttl: 3600  # Cache time-to-live in seconds
  batch_size: 100  # Batch size for bulk operations
  enable_indexing: true
  
  # Integration Settings
  vector_store_sync: true        # Keep vector store and graph in sync
  enable_fallback: true          # Fall back to vector search if graph query fails
  migration_batch_size: 50       # Batch size for migrating existing memories

# =============================================================================
# VALIDATION RULES
# =============================================================================

validation_rules:
  # Node Validation
  required_properties:
    Person: ["name"]
    Company: ["name"]
    Document: ["title", "source"]
    Memory: ["content", "timestamp"]
    
  # Relationship Validation
  bidirectional_relationships: ["RELATES_TO", "CONTRADICTS"]
  temporal_relationships: ["TEMPORAL_SEQUENCE", "DERIVED_FROM"]
  
  # Quality Checks
  max_relationship_distance: 6   # Maximum degrees of separation
  min_node_connections: 1        # Minimum connections per node
  orphan_node_cleanup: true      # Remove isolated nodes
